# Generated by Django 5.2 on 2025-05-04 20:59

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_completed_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
